export { createAudioEngine, type AudioEngine, type AudioEngineOptions } from './webaudio/engine';
export { unlockAudio } from './webaudio/unlock';
export { DEFAULT_SOUND_LAYER, SOUNDS, type SoundEvent, type SoundId } from './events';
export { DEFAULT_LAYER_VOLUMES, LAYERS, LAYER_RULES, type LayerGains, type LayerName } from './layers';
export { soundProfileFromSeed, type SoundProfile } from './profile';
export type { AudioSeed } from './rng';
export { CREAK_SILENT_BELOW, creakShape, type CreakCharacter, type CreakShape } from './creak';
export { MUFFLE, muffleCutoff } from './muffle';
export { STINGER_CLUSTER, stingerShape, type StingerCharacter, type StingerShape } from './stinger';
export { FEVER_SOUND, feverSoundEvents, feverSoundMix, type FeverSoundMix } from './fever';
